global:
  scrape_interval: 5m

scrape_configs:
  - job_name: "cliente-api-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "cliente-api"